services:
  - type: web
    name: didge-moodz
    env: python
    buildCommand: "pip install -r requirements-render.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
